WhiteLagoon.Web/Controllers/BookingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Stripe;
using Stripe.Checkout;
using System.Security.Claims;
using WhiteLagoon.Application.Common.Interfaces;
using WhiteLagoon.Application.Common.Utility;
using WhiteLagoon.Domain.Entities;

namespace WhiteLagoon.Web.Controllers
{
    public class BookingController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public BookingController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }
        [Authorize]
        public IActionResult FinalizeBooking(int villaId, string checkIn, int nights)
        {
            DateOnly checkInDate=DateOnly.Parse(checkIn);
            var claimIdentity = (ClaimsIdentity)User.Identity;
            var UserId = claimIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

            ApplicationUser user = _unitOfWork.User.Get(u=>u.Id == UserId);
            
            Booking booking = new()
            {
                UserId = UserId,
                VillaId = villaId,
                Villa = _unitOfWork.Villa.Get(u=>u.Id==villaId, includeProperties: "VillaAmenity"),
                Nights = nights,
                CheckInDate = checkInDate,
                CheckOutDate = checkInDate.AddDays(nights),
                Phone = user.PhoneNumber,
                Email=user.Email,
                Name = user.Name,   
            };
            
            booking.TotalCost = booking.Villa.Price * nights;

            return View(booking);
        }

        [Authorize]
        [HttpPost]
        public IActionResult FinalizeBooking(Booking booking)
        {
            var villa = _unitOfWork.Villa.Get(u => u.Id == booking.VillaId);

            booking.TotalCost = villa.Price * booking.Nights;

            booking.Status = SD.StatusPending;
            booking.BookingDate = DateTime.Now;

            List<VillaNumber> villaNumbersList=_unitOfWork.VillaNumber.GetAll().ToList();
            List<Booking> bookedVillas= _unitOfWork.Booking.GetAll(u => u.Status == SD.StatusCheckedIn ||
            u.Status == SD.StatusApproved).ToList();

            int roomsAvailable = SD.VillaRoomsAvailable_Count(villa.Id, villaNumbersList, booking.CheckInDate, 
                                                                booking.Nights, bookedVillas);

            if(roomsAvailable==0)
            {
                TempData["error"] = "Room has been sold out!";

                return RedirectToAction(nameof(FinalizeBooking), new
                {
                    villaId = booking.VillaId,
                    checkIn = booking.CheckInDate.ToString(),
                    nights = booking.Nights
                });
            }

            _unitOfWork.Booking.Add(booking);

            _unitOfWork.Save();

            var domain = Request.Scheme+"://"+Request.Host.Value;
            var options = new SessionCreateOptions
            {
                LineItems = new List<SessionLineItemOptions>(),
                Mode = "payment",
                SuccessUrl = domain + $"/booking/BookingConfirmation?bookingId={booking.Id}",
                CancelUrl = domain + $"/booking/FinalizeBooking?villaId={booking.VillaId}&checkIn={booking.CheckOutDate.ToString()}&"
                                   + $"nights={booking.Nights}",
            };

            options.LineItems.Add(new SessionLineItemOptions
            {
                    PriceData = new SessionLineItemPriceDataOptions
                    {
                        UnitAmount = (long)(booking.TotalCost * 100),
                        Currency = "usd",
                        ProductData = new SessionLineItemPriceDataProductDataOptions
                        {
                            Name = villa.Name,
                            //Images = new List<string> { domain + villa.ImageUrl },
                        },
                    },
                    Quantity=1,
            });

            var service = new SessionService();
            Session session = service.Create(options);

            _unitOfWork.Booking.UpdateStripePaymentID(booking.Id, session.Id, session.PaymentIntentId);
            _unitOfWork.Save();


            Response.Headers.Add("Location", session.Url);
            return new StatusCodeResult(303);

            
        }


        [Authorize]
        public IActionResult BookingConfirmation(int bookingId)

        {
            
            Booking bookingFromDb = _unitOfWork.Booking.Get(u => u.Id == bookingId, includeProperties: "User,Villa");

            if (bookingFromDb.Status == SD.StatusPending)
            {
                var service = new SessionService();
                Session session = service.Get(bookingFromDb.StripeSessionId);

                if(session.PaymentStatus == "paid") 
                {
                    _unitOfWork.Booking.UpdateStaturs(bookingFromDb.Id, SD.StatusApproved,0);
                    _unitOfWork.Booking.UpdateStripePaymentID(bookingFromDb.Id, session.Id, session.PaymentIntentId);
                    _unitOfWork.Save();
                }
            }

            return View(bookingId);
        }

        [Authorize]
        public IActionResult BookingDetails(int bookingId)
        {
            Booking objBookings = _unitOfWork.Booking.Get(u => u.Id == bookingId, includeProperties: "User,Villa");

            

            if (objBookings.VillaNumber==0 && objBookings.Status==SD.StatusApproved)
            {
                var availableVillaNumbers = AssignAvailabeVillaNumberByVillaId(objBookings.VillaId);

                objBookings.VillaNumbers=_unitOfWork.VillaNumber.GetAll(u=>u.VillaId==objBookings.VillaId &&
                                                                 availableVillaNumbers.Any(x=>x==u.Villa_Number)).ToList();
            }

            return View(objBookings);
        }


        [HttpPost]
        [Authorize(Roles =SD.Role_Admin)]
        public IActionResult CheckIn(Booking booking)
        {
            _unitOfWork.Booking.UpdateStaturs(booking.Id, SD.StatusCheckedIn, booking.VillaNumber);
            _unitOfWork.Save();

            TempData["success"] = "Booking CheckedIn Successfully!";
            return RedirectToAction(nameof(BookingDetails), new { bookingId = booking.Id });
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Admin)]
        public IActionResult CheckOut(Booking booking)
        {
            _unitOfWork.Booking.UpdateStaturs(booking.Id, SD.StatusCompleted, booking.VillaNumber);
            _unitOfWork.Save();

            TempData["success"] = "Booking CheckedOut Successfully!";
            return RedirectToAction(nameof(BookingDetails), new { bookingId = booking.Id });
        }

        [HttpPost]
        [Authorize]
        public IActionResult CancelBooking(Booking booking)
        {
            _unitOfWork.Booking.UpdateStaturs(booking.Id, SD.StatusCancelled, 0);
            _unitOfWork.Save();

            TempData["success"] = "Booking Cancelled Successfully!";
            return RedirectToAction(nameof(BookingDetails), new { bookingId = booking.Id });
        }

        #region API Calls
        [HttpGet]
        [Authorize]
        public IActionResult GetAll(string status)
        {
            IEnumerable<Booking> objBookings;

            if(User.IsInRole(SD.Role_Admin))
            {
                objBookings=_unitOfWork.Booking.GetAll(includeProperties:"User,Villa");
            }
            else 
            {
                var claimIdentity = (ClaimsIdentity)User.Identity;
                var UserId = claimIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

                objBookings = _unitOfWork.Booking.GetAll(u=>u.UserId == UserId, includeProperties: "User,Villa");
            }
            if(!string.IsNullOrEmpty(status))
            {
                objBookings = objBookings.Where(u => u.Status.ToLower().Equals(status.ToLower()));
            }
            return Json (new { data = objBookings });
        }

        private List<int> AssignAvailabeVillaNumberByVillaId(int villaId)
        {
            List<int> availableVillaNumbers = new();

            List<int> villaNumbers = _unitOfWork.VillaNumber.GetAll(u => u.VillaId == villaId).Select(x => x.Villa_Number).ToList();

            List<int> bookedVillaNumbers = _unitOfWork.Booking.GetAll(u => u.VillaId == villaId &&
                                           (u.Status==SD.StatusApproved || u.Status == SD.StatusCheckedIn))
                                           .Select(x => x.VillaNumber).ToList();

            foreach (var villanumber in villaNumbers)
            {
                if (!bookedVillaNumbers.Contains(villanumber))
                {
                    availableVillaNumbers.Add(villanumber);
                }
            }

            return availableVillaNumbers;
        }
        #endregion
    }
}

WhiteLagoon.Web/Views/Booking/BookingConfirmation.cshtml
@model int

<div class="container  pt-4">
    <div class="col-12 text-center">
        <h1 class="text-success text-center">Your Vacation is Confirmed!</h1>
        Your Order Number is : @Model <br />
        <p>You can view all order details in Manage Order Section.</p>
        <img src="~/Static_Files/Images/App-Images/orderConfirmed.jpg" style="border-radius:20px" width="65%" />
    </div>
    <div class="col-12 text-center text-warning">
        <p class="pt-1">Pack your bags! You are one step closer to an amazing vacation!</p>
    </div>
</div>

WhiteLagoon.Web/Views/Booking/BookingDetails.cshtml
@model Booking


<div class="p-4 mt-0 mt-lg-4">
    <div class="row" style="border: 1px solid #aaa;">

        <div class="col-12 col-lg-6 p-4 2 mt-2 mt-md-0">
            <div class="row p-1 " style="border-radius:20px; ">
                <div class="col-6">
                    <h3 class="text-success">Villa Details</h3>
                </div>
                <div class="col-6 text-end">
                    <a asp-controller="Booking" asp-action="Index" asp-route-status="Approved" class="btn btn-secondary my-2">
                        <i class="bi bi-arrow-left-circle"></i> Back to Bookings</a>
                </div>
                <hr />
                <partial name="_VillaDetail" model="@Model.Villa" />
                <hr />
                <div class="text-end">
                    <h4 class="text-danger font-weight-bold ">
                        Booking Total :
                        <span style="border-bottom:1px solid #ff6a00">
                            @Model.TotalCost.ToString("c")
                        </span>
                    </h4>
                </div>
                <hr>

                <form method="post">
                    <div class="row pt-1 mb-3 " style="border-radius:20px; ">
                        <div class="col-12 text-center">

                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-12 col-lg-6 p-4 2 mt-4 mt-md-0" style="border-left:1px solid #aaa">
            <form method="post">
                <input  asp-for="Id" hidden />
                
                <div class="row pt-1 mb-3 " style="border-radius:20px; ">
                    <div class="col-6">
                        <h3 class="text-success">Enter Booking Details</h3>
                    </div>
                    <div class="col-6">
                        @if ((@Model.Status == SD.StatusApproved) || (@Model.Status == SD.StatusPending))
                        {
                            <button asp-action="CancelBooking" type="submit" class="btn btn-sm btn-outline-danger form-control my-1">
                                <i class="bi bi-x-circle"></i> &nbsp; Cancel Booking
                            </button>
                        }  
                    </div>
                </div>
                <div class="row">
                    <div class="form-group pt-2 col-6">
                        <label class="text-warning">Name</label>
                        <input asp-for="Name" class="form-control" />
                    </div>
                    <div class="form-group pt-2 col-6">
                        <label class="text-warning">Phone</label>
                        <input asp-for="Phone" class="form-control" />
                    </div>
                    <div class="form-group pt-2 col-6">
                        <label class="text-warning">Email</label>
                        <input asp-for="Email" class="form-control" />
                    </div>
                    <div class="form-group pt-2 col-6">
                        <label class="text-warning">No. of nights</label>
                        <input asp-for="Nights" disabled class="form-control" />
                    </div>
                    <div class="form-group pt-2 col-6">
                        <label class="text-warning">Status</label>
                        <input asp-for="Status" disabled class="form-control" />
                    </div>
                    <div class="form-group pt-2 col-6">
                        <label class="text-warning">Booking Date</label>
                        <input asp-for="BookingDate" disabled class="form-control" />
                    </div>
                    <div class="form-group pt-2 col-6">
                        <label class="text-warning">Check In Date</label>
                        <input asp-for="CheckInDate" disabled class="form-control" />
                    </div>
                    <div class="form-group pt-2 col-6">
                        <label class="text-warning">Actual Check In Date</label>
                        <input asp-for="ActualCheckInDate" disabled class="form-control" />
                    </div>
                    <div class="form-group pt-2 col-6">
                        <label class="text-warning">Check Out Date</label>
                        <input asp-for="CheckOutDate" disabled class="form-control" />
                    </div>
                    <div class="form-group pt-2 col-6">
                        <label class="text-warning">Actual Check Out Date</label>
                        <input asp-for="ActualCheckOutDate" disabled class="form-control" />
                    </div>
                    @if(User.IsInRole(SD.Role_Admin) && @Model.Status==SD.StatusApproved)
                    {
                        <div class="form-group pt-2 col-6">
                            <label class="text-danger" asp-for="VillaNumber">Villa Number</label>
                            <select asp-for="VillaNumber"  class="form-control border shadow">
                                @foreach(var villaNumber in @Model.VillaNumbers)
                                {
                                    <option value="@villaNumber.Villa_Number" >@villaNumber.Villa_Number</option>
                                }
                            </select>
                        </div>
                    }

                    else if (@Model.Status == SD.StatusCheckedIn || @Model.Status == SD.StatusCompleted)
                    {
                        <div class="form-group pt-2 col-6">
                            <label class="text-warning" asp-for="VillaNumber">Villa Number</label>
                            <input asp-for="VillaNumber" readonly class="form-control" />
                        </div>
                    }

                    <div class="form-group pt-2 col-6">
                        <label class="text-warning">Status</label>
                        <input asp-for="Status" disabled class="form-control" />
                    </div>

                    @if (User.IsInRole(SD.Role_Admin) && Model.IsPaymentSuccessful)
                    {
                        <div class="form-group pt-2 col-6">
                            <label class="text-warning">Payment Intent ID</label>
                            <input asp-for="StripePaymentIntentId" disabled class="form-control" />
                        </div>
                        <div class="form-group pt-2 col-6">
                            <label class="text-warning">Stripe Session ID</label>
                            <input asp-for="StripeSessionId" disabled class="form-control" />
                        </div>
                        <div class="form-group pt-2 col-6">
                            <label class="text-warning">Payment Date</label>
                            <input asp-for="PaymentDate" disabled class="form-control" />
                        </div>

                    }

                    <div class="form-group pt-2 pt-md-4">
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            if (Model.Status == SD.StatusApproved)
                            {
                                <button asp-controller="Booking" asp-action="CheckIn" type="submit"  class="btn btn-warning form-control my-1">
                                    <i class="bi bi-check2-square"></i> &nbsp; Check In
                                </button>
                            }

                            @if (Model.Status == SD.StatusCheckedIn)
                            {
                                <button asp-controller="Booking" asp-action="CheckOut" type="submit" class="btn btn-success form-control my-1">
                                    <i class="bi bi-clipboard2-check"></i> &nbsp; Check Out / Complete Booking
                                </button>
                            }

                        }


                    </div>
            </form>
        </div>
    </div>
</div>

WhiteLagoon.Web/Views/Booking/FinalizeBooking.cshtml
@using Microsoft.AspNetCore.Components;
@model Booking

<div class="container pt-4 mt-0 mt-lg-4">
    <div class="row" style="border: 1px solid #aaa;">

        <div class="col-12 col-lg-7 p-4 2 mt-4 mt-md-0">
            <div class="row p-1 my-1 " style="border-radius:20px; ">
                <div class="col-6">
                    <h3 class="text-success">Villa Details</h3>
                </div>
                <div class="text-end col-6 ">
                    <a class="btn btn-sm btn-outline-danger" style="width:200px;"
                       asp-controller="Home" asp-action="Index"><i class="bi bi-arrow-left-square"></i> &nbsp; Modify Selection</a>
                </div>
                <hr />
                <partial name="_VillaDetail" model="@Model.Villa" />
                <hr />
                <div class="text-end">
                    <h4 class="text-danger font-weight-bold ">
                        Booking Total :
                        <span style="border-bottom:1px solid #ff6a00">
                            @Model.TotalCost.ToString("c")
                        </span>
                    </h4>
                </div>
            </div>
        </div>
        <div class="col-12 col-lg-5 p-4 2 mt-4 mt-md-0" style="border-left:1px solid #aaa">

            <form method="post">

                <input asp-for="VillaId" hidden />
                <input asp-for="UserId" hidden />
                <input asp-for="CheckInDate" hidden />
                <input asp-for="CheckOutDate" hidden />
                <input asp-for="Nights" hidden />

                <div class="row pt-1 mb-3 " style="border-radius:20px; ">
                    <div class="col-12">
                        <h3 class="text-success">Enter Booking Details</h3>
                    </div>
                </div>

                <div class="form-group pt-0">
                    <label asp-for="Name" class="text-warning">Name</label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger" ></span>
                </div>
                <div class="form-group pt-2">
                    <label asp-for="Phone" class="text-warning">Phone</label>
                    <input asp-for="Phone" class="form-control" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
                <div class="form-group pt-2">
                    <label asp-for="Email" class="text-warning">Email</label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group pt-2">
                    <label asp-for="CheckInDate" class="text-warning">Check in Date</label>
                    <input asp-for="CheckInDate" disabled class="form-control" />
                </div>
                <div class="form-group pt-2">
                    <label asp-for="CheckOutDate" class="text-warning">Check Out Date</label>
                    <input asp-for="CheckOutDate" disabled class="form-control" />
                </div>
                <div class="form-group pt-2">
                    <label asp-for="Nights"  class="text-warning">No. of nights</label>
                    <input asp-for="Nights" disabled class="form-control" />
                </div>
                <div class="form-group pt-2 pt-md-4">
                    @if (@Model.Villa.isAvailable)
                    {
                    <button type="submit" class="btn btn-success form-control">Looks Good! Checkout Now</button>
                    }
                    else
                    {
                    <input class="btn btn-danger disabled form-control" value="Sold Out" />
                    }
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

WhiteLagoon.Web/Views/Booking/Index.cshtml
@{
    var status = Context.Request.Query["status"].ToString().ToLower();

    var pending=""; 
    var approved = "";
    var checkedIn = "";
    var completed = "";
    var cancelled = "";

    switch(status)
    {
        case "pending":
            pending = "text-white bg-success";
            break;
        case "approved":
            approved = "text-white bg-success";
            break;
        case "checkedin":
            checkedIn = "text-white bg-success";
            break;
        case "completed":
            completed = "text-white bg-success";
            break;
        case "cancelled":
            cancelled = "text-white bg-success";
            break;
        default:
            break;
    }
}

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2"> Booking List</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <div class="d-flex justify-content-end pb-4 pt-2">
            <ul class="list-group list-group-horizontal-sm">
                <a style="text-decoration:none;" asp-route-status="@SD.StatusPending" asp-controller="Booking" asp-action="Index">
                    <li class="list-group-item @pending">
                        Pending
                    </li>
                </a>
                <a style="text-decoration:none;" asp-route-status="@SD.StatusApproved" asp-controller="Booking" asp-action="Index">
                <li class="list-group-item @approved">
                        Approved
                    </li>
                </a>
                <a style="text-decoration:none;" asp-route-status="@SD.StatusCheckedIn" asp-controller="Booking" asp-action="Index">
                <li class="list-group-item @checkedIn">
                        CheckedIn
                    </li>
                </a>
                <a style="text-decoration:none;" asp-route-status="@SD.StatusCompleted" asp-controller="Booking" asp-action="Index">
                <li class="list-group-item @completed">
                        Completed
                    </li>
                </a>
                <a style="text-decoration:none;" asp-route-status="@SD.StatusCancelled" asp-controller="Booking" asp-action="Index">
                <li class="list-group-item @cancelled">
                        Cancelled
                    </li>
                </a>
            </ul>
        </div>
        <table id="tblbookings" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Phone</th>
                    <th>Email</th>
                    <th>Status</th>
                    <th>Check In Date</th>
                    <th>Nights</th>
                    <th>TotalCost</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>
    </div>
</div>

@section Scripts {
    <script src="~/js/booking.js"></script>
}