WhiteLagoon.Web/Controllers/AmenityController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WhiteLagoon.Application.Common.Interfaces;
using WhiteLagoon.Application.Common.Utility;
using WhiteLagoon.Domain.Entities;
using WhiteLagoon.Infrastructure.Data;
using WhiteLagoon.Web.ViewModels;

namespace WhiteLagoon.Web.Controllers
{
    [Authorize(Roles =SD.Role_Admin)]
    public class AmenityController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public AmenityController(IUnitOfWork unitOfWork,IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork= unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            var villas = _unitOfWork.Amenity.GetAll(includeProperties: "Villa");
            return View(villas);
        }
        public IActionResult Create()
        {
            AmenityVM amenityVM = new()
            {
                VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                })
            };
            //ViewData["VillaList"] = list;
            //ViewBag.VillaList = list;

            return View(amenityVM);
        }

        [HttpPost]
        public IActionResult Create(AmenityVM obj)
        {

            // ModelState.Remove("Villa");
            if (ModelState.IsValid)
            {
                _unitOfWork.Amenity.Add(obj.Amenity);
                _unitOfWork.Save();
                TempData["success"] = "Amenity has been created successfully!";
                return RedirectToAction(nameof(Index));
            }

            TempData["error"] = "Amenity could not be created!";
            return View();

        }
        public IActionResult Update(int amenityId)
        {
            Amenity? obj = _unitOfWork.Amenity.Get(u => u.Id == amenityId);

            if (obj is null)
            {
                return RedirectToAction("Error", "Home");
            }

            AmenityVM amenityVM = new()
            {
                Amenity = obj,
                VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                })
            };

            return View(amenityVM);
        }

        [HttpPost]
        public IActionResult Update(AmenityVM obj)
        {
            bool check = _unitOfWork.Amenity.Any(u => u.Id == obj.Amenity.Id);

            if (ModelState.IsValid && check)
            {
                _unitOfWork.Amenity.Update(obj.Amenity);
                _unitOfWork.Save();
                TempData["success"] = "Amenity has been updated successfully!";
                return RedirectToAction(nameof(Index));
            }

            TempData["error"] = "Amenity could not be updated!";
            return View();
        }

        public IActionResult Delete(int amenityId)
        {
            Amenity? obj = _unitOfWork.Amenity.Get(u => u.Id == amenityId);

            if (obj is null)
            {
                return RedirectToAction("Error", "Home");
            }

            AmenityVM amenityVM = new()
            {
                Amenity = obj,
                VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                })
            };

            return View(amenityVM);
        }

        [HttpPost]
        public IActionResult Delete(AmenityVM obj)
        {
            bool check = _unitOfWork.Amenity.Any(u => u.Id == obj.Amenity.Id);

            if (check)
            {
                _unitOfWork.Amenity.Remove(obj.Amenity);
                _unitOfWork.Save();
                TempData["success"] = "Amenity has been deleted successfully!";
                return RedirectToAction(nameof(Index));
            }
            TempData["error"] = "Villa could not be deleted!";
            return View();
        }
    }
}

WhiteLagoon.Web/Controllers/VillaNumberController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WhiteLagoon.Application.Common.Interfaces;
using WhiteLagoon.Domain.Entities;
using WhiteLagoon.Infrastructure.Data;
using WhiteLagoon.Web.ViewModels;

namespace WhiteLagoon.Web.Controllers
{
    public class VillaNumberController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public VillaNumberController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            var villas = _unitOfWork.VillaNumber.GetAll(includeProperties: "Villa").OrderBy(x => x.VillaId);
            return View(villas);
        }
        public IActionResult Create()
        {
            VillaNumberVM villaNumberVM = new()
            {
                VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                })
            };
            //ViewData["VillaList"] = list;
            //ViewBag.VillaList = list;

            return View(villaNumberVM);
        }
        [HttpPost]
        public IActionResult Create(VillaNumberVM obj)
        {
            //ModelState.Remove("Villa");
            bool roomNumberExists = _unitOfWork.VillaNumber.Any(u => u.Villa_Number == obj.VillaNumber.Villa_Number);

            if (roomNumberExists)
            {
                TempData["error"] = "This VillaNumber exists!";
                obj.VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                });
                return View(obj);
            }

            if (ModelState.IsValid)
            {
                _unitOfWork.VillaNumber.Add(obj.VillaNumber);
                _unitOfWork.Save();
                TempData["success"] = "VillaNumber has been created successfully!";
                return RedirectToAction(nameof(Index));
            }

            TempData["error"] = "VillaNumber could not be created!";
            return View();
            
        }
        public IActionResult Update(int villaNumberId)
        {
            VillaNumber? obj = _unitOfWork.VillaNumber.Get(u => u.Villa_Number == villaNumberId);
            if (obj is null)
            {
                return RedirectToAction("Error", "Home");
            }

            VillaNumberVM villaNumberVM = new()
            {
                VillaNumber = obj,
                VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                })
            };
            return View(villaNumberVM);
        }

        [HttpPost]
        public IActionResult Update(VillaNumberVM obj)
        {
            

            if (ModelState.IsValid)
            {
                _unitOfWork.VillaNumber.Update(obj.VillaNumber);
                _unitOfWork.Save();
                TempData["success"] = "VillaNumber has been updated successfully!";
                return RedirectToAction(nameof(Index));
            }

            obj.VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            return View(obj);

        }

        public IActionResult Delete(int villaNumberId)
        {
            VillaNumber? obj = _unitOfWork.VillaNumber.Get(u => u.Villa_Number == villaNumberId);
            if (obj is null)
            {
                 return RedirectToAction("Error", "Home");
            }

            VillaNumberVM villaNumberVM = new()
            {
                VillaNumber = obj,
                VillaList = _unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                })
            };
            return View(villaNumberVM);
        }

        [HttpPost]
        public IActionResult Delete(VillaNumberVM obj)
        {
            VillaNumber? objFromDb = _unitOfWork.VillaNumber.Get(u => u.Villa_Number == obj.VillaNumber.Villa_Number);

            if (objFromDb is not null)
            {
                _unitOfWork.VillaNumber.Remove(objFromDb);
                _unitOfWork.Save();
                TempData["success"] = "VillaNumber has been deleted successfully!";
                return RedirectToAction(nameof(Index));

            }
            TempData["error"] = "VillaNumber could not be deleted!";
            return View();

        }
    }
}

WhiteLagoon.Web/Views/Amenity/Create.cshtml
@model AmenityVM


<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">
                    Create Amenity
                </h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post">

            <div class="p-3">
                @* <div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-floating py-3 col-12">

                    @* <select asp-for="@Model.VillaId" asp-items="@ViewData["VillaList"] as IEnumerable<SelectListItem>"
                    <select asp-for="@Model.VillaNumber.VillaId" asp-items="@ViewBag.VillaList" *@
                    <select asp-for="@Model.Amenity.VillaId" asp-items="@Model.VillaList"
                            class="form-control border shadow">

                        <option selected disabled>--Select Villa Name--</option>

                    </select>

                    <label asp-for="Amenity.VillaId" class="ms-2"></label>
                    <span asp-validation-for="Amenity.VillaId" class="text-danger"></span>
                </div>
                <div class="form-floating py-3 col-12">
                    <input asp-for="Amenity.Name" class="form-control border shadow" />
                    <label asp-for="Amenity.Name" class="ms-2"></label>
                    <span asp-validation-for="Amenity.Name" class="text-danger"></span>
                </div>
                <div class="form-floating py-3 col-12">
                    <input asp-for="Amenity.Description" class="form-control border shadow" />
                    <label asp-for="Amenity.Description" class="ms-2"></label>
                    <span asp-validation-for="Amenity.Description" class="text-danger"></span>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class=" btn btn-success w-100">
                            Create Villa Number
                        </button>
                    </div>
                    <div class="col-6  col-md-3">
                        <a asp-controller="VillaNumber" asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-plus-circle"></i> Cancel
                        </a>
                    </div>
                </div>
            </div>

        </form>

    </div>
</div>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial.cshtml" />
    }
}

WhiteLagoon.Web/Views/Amenity/Delete.cshtml
@model AmenityVM


<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">
                    Update Amenity
                </h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post">
            <input type="hidden" asp-for="@Model.Amenity.Id" />
            <div class="p-3">
                @* <div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-floating py-3 col-12">

                    @* <select asp-for="@Model.VillaId" asp-items="@ViewData["VillaList"] as IEnumerable<SelectListItem>"
                    <select asp-for="@Model.VillaNumber.VillaId" asp-items="@ViewBag.VillaList" *@
                    <select asp-for="@Model.Amenity.VillaId" disabled asp-items="@Model.VillaList"
                            class="form-control border shadow">
                    </select>

                    <label asp-for="Amenity.VillaId" class="ms-2"></label>
                    <span asp-validation-for="Amenity.VillaId" class="text-danger"></span>
                </div>
                <div class="form-floating py-3 col-12">
                    <input asp-for="Amenity.Name" readonly class="form-control border shadow" />
                    <label asp-for="Amenity.Name" class="ms-2"></label>
                    <span asp-validation-for="Amenity.Name" class="text-danger"></span>
                </div>
                <div class="form-floating py-3 col-12">
                    <input asp-for="Amenity.Description" readonly class="form-control border shadow" />
                    <label asp-for="Amenity.Description" class="ms-2"></label>
                    <span asp-validation-for="Amenity.Description" class="text-danger"></span>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class=" btn btn-danger w-100">
                            Delete Amenity
                        </button>
                    </div>
                    <div class="col-6  col-md-3">
                        <a asp-controller="Amenity" asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-plus-circle"></i> Cancel
                        </a>
                    </div>
                </div>
            </div>

        </form>

    </div>
</div>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial.cshtml" />
    }
}

WhiteLagoon.Web/Views/Amenity/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<Amenity>

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2"> Amenity List</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <div class="row pb-3">
            <div class="col-6 offset-6 text-end">
                <a asp-controller="Amenity" asp-action="Create" class="btn btn-secondary">
                    <i class="bi bi-plus-circle"></i> Create New Amenity
                </a>
            </div>
        </div>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Villa Name</th>
                    <th>Name</th>
                    <th>Description</th>

                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td>@obj.Villa.Name</td>
                        <td>@obj.Name</td>
                        <td>@obj.Description</td>

                        <td>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Amenity" asp-action="Update" asp-route-amenityId="@obj.Id"
                                   class="btn btn-success mx-2">
                                    <i class="bi bi-pencil-square"></i> Edit
                                </a>
                                <a asp-controller="Amenity" asp-action="Delete" asp-route-amenityId="@obj.Id"
                                   class="btn btn-danger mx-2">
                                    <i class="bi bi-trash-fill"></i> Delete
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

WhiteLagoon.Web/Views/Amenity/Update.cshtml
@model AmenityVM


<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">
                    Update Amenity
                </h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post">
            <input type="hidden" asp-for="@Model.Amenity.Id" />
            <div class="p-3">
                @* <div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-floating py-3 col-12">

                    @* <select asp-for="@Model.VillaId" asp-items="@ViewData["VillaList"] as IEnumerable<SelectListItem>"
                    <select asp-for="@Model.VillaNumber.VillaId" asp-items="@ViewBag.VillaList" *@
                    <select asp-for="@Model.Amenity.VillaId" asp-items="@Model.VillaList"
                            class="form-control border shadow">
                    </select>

                    <label asp-for="Amenity.VillaId" class="ms-2"></label>
                    <span asp-validation-for="Amenity.VillaId" class="text-danger"></span>
                </div>
                <div class="form-floating py-3 col-12">
                    <input asp-for="Amenity.Name"  class="form-control border shadow" />
                    <label asp-for="Amenity.Name" class="ms-2"></label>
                    <span asp-validation-for="Amenity.Name" class="text-danger"></span>
                </div>
                <div class="form-floating py-3 col-12">
                    <input asp-for="Amenity.Description" class="form-control border shadow" />
                    <label asp-for="Amenity.Description" class="ms-2"></label>
                    <span asp-validation-for="Amenity.Description" class="text-danger"></span>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class=" btn btn-success w-100">
                            Update Amenity
                        </button>
                    </div>
                    <div class="col-6  col-md-3">
                        <a asp-controller="Amenity" asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-plus-circle"></i> Cancel
                        </a>
                    </div>
                </div>
            </div>

        </form>

    </div>
</div>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial.cshtml" />
    }
}